### PR TITLE
Add support for Kodi 19 (kodi libs and python3)

### PR DESCRIPTION
**Pull request by RSantos94**
Fixed problems on loading add-on on start-up for Kodi 19

Known issue: broken login error 33804

### CODE REVIEW

**Comment by JosemyAB** [comment]
I have raspbian with python version 2.7.16. If I update to phyton 3, will the rest of the applications that I have in my raspberry work?

**Review by JosemyAB — APPROVED** [review]

**Comment by RSantos94** [comment]
> 
> 
> I have raspbian with python version 2.7.16. If I update to phyton 3, will the rest of the applications that I have in my raspberry work?

I'm not sure. I've got Python basically just for this. But probably, since from 2 to 3 also broke this plug-in

**Comment by panizza** [comment]
> Fixed problems on loading add-on on start-up for Kodi 19
> 
> Known issue: broken login error 33804

I just downloaded and installed your fork, but error 33804 is still there

**Comment by RSantos94** [comment]
> 
> 
> > Fixed problems on loading add-on on start-up for Kodi 19
> > Known issue: broken login error 33804
> 
> I just downloaded and installed your fork, but error 33804 is still there

Yeah. I couldn't fix that :/ I tried, but to no avail

**Comment by panizza** [comment]
Ok, I'll take a look and let you know asap

**Comment by panizza** [comment]
@RSantos94 
I fixed every single errore I was able to found and I created a pull request in your repo https://github.com/RSantos94/script.tvtime/pull/1

**Review by the-lazy-fox — APPROVED** [review]

**Comment by jupiler5** [comment]
That works, thanks a lot !

**Comment by panizza** [comment]
@the-lazy-fox can you please create a new package for the plugin? And as @jupiler5 asked here https://github.com/RSantos94/script.tvtime/pull/1#issuecomment-801271029 could you update information in addon.xml ("increase" script version, website, source... and maybe provider-name, such as "alxlaxv - updated by Panizza & RSantos94").

**Comment by majidorc** [comment]
> @the-lazy-fox can you please create a new package for the plugin? And as @jupiler5 asked here [RSantos94#1 (comment)](https://github.com/RSantos94/script.tvtime/pull/1#issuecomment-801271029) could you update information in addon.xml ("increase" script version, website, source... and maybe provider-name, such as "alxlaxv - updated by Panizza & RSantos94").

Error 33804 again :(

**Pull request merged**
